### ISSUE TITLE
Specifying a country name different country name yields to multiple country packages in environment

### ISSUE THREAD

**Issue by guillett** [openfisca/country-template#14]
Hi,

Great stuff !  🙂

I used your snippet to create a country package. I changed the `COUNTRY_NAME` but when I started `openfisca-serve --port 2000` it generated the following warning:

````
WARNING: Several country packages detected : `openfisca_france, openfisca_speed`. Using `openfisca_france` by default. To use another package, please use the --country_package option.
````

When I specify _my_ country package (ie. `openfisca-serve --port 2000 --country_package openfisca_speed`), I get the following error:

```
/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:724: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
ERROR: Unable to load OpenFisca variables from file "/repos/openfisca_speed/openfisca-speed/openfisca_speed/variables/benefits.py"
Traceback (most recent call last):
  File "/usr/local/bin/openfisca-serve", line 11, in <module>
    load_entry_point('OpenFisca-Web-API', 'console_scripts', 'openfisca-serve')()
  File "/repos/openfisca-web-api/openfisca_web_api/scripts/serve.py", line 32, in main
    app = make_app({}, **conf)
  File "/repos/openfisca-web-api/openfisca_web_api/application.py", line 72, in make_app
    environment.load_environment(global_conf, app_conf)
  File "/repos/openfisca-web-api/openfisca_web_api/environment.py", line 102, in load_environment
    tax_benefit_system = country_package.CountryTaxBenefitSystem()
  File "openfisca_speed/__init__.py", line 21, in __init__
    self.add_variables_from_directory(os.path.join(COUNTRY_DIR, 'variables'))
  File "/usr/local/lib/python2.7/site-packages/openfisca_core/taxbenefitsystems.py", line 197, in add_variables_from_directory
    self.add_variables_from_file(py_file)
  File "/usr/local/lib/python2.7/site-packages/openfisca_core/taxbenefitsystems.py", line 186, in add_variables_from_file
    self.add_variable(pot_variable)
  File "/usr/local/lib/python2.7/site-packages/openfisca_core/taxbenefitsystems.py", line 158, in add_variable
    return self.load_variable(variable, update = False)
  File "/usr/local/lib/python2.7/site-packages/openfisca_core/taxbenefitsystems.py", line 145, in load_variable
    column = variable.to_column(self)
  File "/usr/local/lib/python2.7/site-packages/openfisca_core/variables.py", line 58, in to_column
    **self.attributes
  File "/usr/local/lib/python2.7/site-packages/openfisca_core/formulas.py", line 910, in new_filled_column
    ', '.join(sorted(specific_attributes.iterkeys())))
AssertionError: Unexpected attributes in definition of variable "basic_income": 'formula_2015_12, formula_2016_12'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

Am I doing something wrong ?

Great thanks !

Here is the snippet I used:

```bash
COUNTRY_NAME=Speed  # set the name of your country here; you should keep all capitals, and replace any spaces in the name by underscores
URL=https://github.com/openfisca/openfisca-france  # set here the URL of the repository where you will publish your code.

lowercase_country_name=$(echo $COUNTRY_NAME | tr '[:upper:]' '[:lower:]')

git clone https://github.com/openfisca/country-template.git  # download this template code

# remove all references to `openfisca_country_template` in the code base:
mv country-template openfisca-$lowercase_country_name
cd openfisca-$lowercase_country_name
git remote remove origin
sed -i '' '3,28d' README.md  # Remove these instructions lines
sed -i '' "s|country_template|$lowercase_country_name|g" README.md setup.py check-version-bump.sh Makefile `find openfisca_country_template -type f`
sed -i '' "s|country-template|$lowercase_country_name|g" README.md
sed -i '' "s|Country-Template|$COUNTRY_NAME|g" README.md setup.py check-version-bump.sh .github/PULL_REQUEST_TEMPLATE.md CONTRIBUTING.md `find openfisca_country_template -type f`
sed -i '' "s|https://github.com/openfisca/openfisca-country-template|$URL|g" setup.py
mv openfisca_country_template openfisca_$lowercase_country_name
```

Here is the full log (ie. commands and stdout/stderr):
```
COUNTRY_NAME=Speed  # set the name of your country here; you should keep all capitals, and replace any spaces in the name by underscores
URL=https://github.com/openfisca/openfisca-france  # set here the URL of the repository where you will publish your code.

lowercase_country_name=$(echo $COUNTRY_NAME | tr '[:upper:]' '[:lower:]')

git clone https://github.com/openfisca/country-template.git  # download this template code

# remove all references to `openfisca_country_template` in the code base:
mv country-template openfisca-$lowercase_country_name
cd openfisca-$lowercase_country_name
git remote remove origin
sed -i '' '3,28d' README.md  # Remove these instructions lines
sed -i '' "s|country_template|$lowercase_country_name|g" README.md setup.py check-version-bump.sh Makefile `find openfisca_country_template -type f`
sed -i '' "s|country-template|$lowercase_country_name|g" README.md
sed -i '' "s|Country-Template|$COUNTRY_NAME|g" README.md setup.py check-version-bump.sh .github/PULL_REQUEST_TEMPLATE.md CONTRIBUTING.md `find openfisca_country_template -type f`
sed -i '' "s|https://github.com/openfisca/openfisca-country-template|$URL|g" setup.py
mv openfisca_country_template openfisca_$lowercase_country_name
```

**Comment by fpagnoux** [comment]
Hi @guillett !

Thanks for reaching to us.

>WARNING: Several country packages detected : `openfisca_france, openfisca_speed`. Using `openfisca_france` by default. To use another package, please use the --country_package option.

Did you have `openfisca_france` installed in your environment before starting to build your country package from the template ? 
If so the warning is normal : it is just letting you know that several country package were detected in your environment. As OpenFisca doesn't know which one to choose, it picks one and warn you about it. 
If not, something weird happened, and I haven't been able to reproduce it. Can you try again from a clean environment, and run `pip list` before and after running the snipper ?

As for the error, it seems that an old version of `OpenFisca-Core` is installed on your computer.  This template requires an version `>= 14.0.0`. Can you please also run `pip list` to know what's on our environment ?

Thanks !

**Comment by guillett** [comment]
@fpagnoux you are completely right, my apologies.

I thought I started with a clean environment but I am a fool.

Here is the `pip list` output.

```
appnope (0.1.0)
Babel (2.4.0)
backports.shutil-get-terminal-size (1.0.0)
Biryani (0.10.4)
certifi (2017.4.17)
chardet (3.0.4)
click (6.7)
decorator (4.0.11)
dpath (1.4.0)
enum34 (1.1.6)
Flask (0.12)
Flask-Cors (3.0.2)
gunicorn (19.7.1)
idna (2.5)
ipython (5.4.1)
ipython-genutils (0.2.0)
isodate (0.5.4)
itsdangerous (0.24)
Jinja2 (2.9.6)
lxml (3.8.0)
MarkupSafe (1.0)
numpy (1.12.1)
OpenFisca-Core (14.0.1, /repos/openfisca-core)
OpenFisca-France (18.6.2, /repos/openfisca-france)
OpenFisca-Speed (1.2.2, /repos/openfisca_speed/openfisca-speed)
OpenFisca-Web-API (5.1.3)
Paste (2.0.3)
PasteDeploy (1.5.2)
pathlib2 (2.3.0)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.14)
ptyprocess (0.5.2)
Pygments (2.2.0)
pytz (2017.2)
PyYAML (3.12)
requests (2.18.1)
scandir (1.5)
setuptools (36.0.1)
simplegeneric (0.8.1)
six (1.10.0)
Tempita (0.5.2)
traitlets (4.3.2)
urllib3 (1.21.1)
wcwidth (0.1.7)
WebError (0.13.1)
WebOb (1.7.2)
Werkzeug (0.12.2)
wheel (0.29.0)
```

**Comment by fpagnoux** [comment]
Ok, great ! I'm thus closing the issue.
